---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp postcss.config.cjs $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp postcss.config.cjs $DEPLOYPATH
    - /bin/cp tailwind.config.cjs $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp yarn.lock $DEPLOYPATH
